stage:
  before:
    - export SECRET_KEY_BASE=abc
    - bundle exec rake sandbox
    - cd sandbox
    - ln -sf $PWD/public $PWD/../public
    - cp ../config/initializers/teatro_patches.rb config/initializers/

  run:
    # workdir is sandbox
    - bundle exec rails server

  database:
    - echo "skip database stage. rake sandbox already did everything"

config:
  database: postgresql
  services:
    - postgresql
