language: ruby

env:
  global:
    - DISCOURSE_HOSTNAME=www.example.com
    - RUBY_GC_MALLOC_LIMIT=50000000
  matrix:
    - "RAILS_MASTER=0"
    - "RAILS42=1"
    - "RAILS_MASTER=1"

addons:
  postgresql: 9.3
  apt:
    packages:
    - gifsicle
    - jpegoptim
    - optipng
    - jhead

matrix:
  allow_failures:
    - env: "RAILS_MASTER=1"
    - env: "RAILS42=1"
    - rvm: rbx-2
  fast_finish: true

rvm:
  - 2.0.0
  - 2.1
  - 2.2

services:
  - redis-server

sudo: false

cache:
  directories:
    - vendor/bundle

before_install:
  - gem install bundler
  - npm i -g eslint babel-eslint
  - eslint app/assets/javascripts
  - eslint --ext .es6 app/assets/javascripts
  - eslint --ext .es6 test/javascripts
  - eslint test/javascripts

before_script:
  - bundle exec rake db:create db:migrate

install:
  - bash -c "if [ '$RAILS42' == '1' ]; then bundle update --retry=3 --jobs=3 rails rails-observers; fi"
  - bash -c "if [ '$RAILS_MASTER' == '1' ]; then bundle update --retry=3 --jobs=3 arel rails rails-observers seed-fu; fi"
  - bash -c "if [ '$RAILS_MASTER' == '0' ]; then bundle install --without development --deployment --retry=3 --jobs=3; fi"

script: 'bundle exec rspec && bundle exec rake plugin:spec && bundle exec rake qunit:test'
